import { SubstanceDefinition } from './types';

export const SUBSTANCES: SubstanceDefinition[] = [
  {
    id: 'alcohol',
    name: 'Alcohol LLC',
    tagline: 'The Foundation of Bad Decisions',
    description: 'The quiet villain. Seems harmless early, multiplies everything else.',
    baseCost: 10,
    costMultiplier: 1.15,
    baseVibes: 0.5,
    energyMod: -0.2,
    chaosMod: 0.5,
    strainMod: 0.3,
    hydrationMod: 0.5,
    sleepDebtMod: 0,
    memoryMod: -0.4,
    confidenceMod: 1,
  },
  {
    id: 'stimulant',
    name: 'Stimulant Startups',
    tagline: 'Sleep is a Construct',
    description: 'Energy boosts, time extension, but the bill comes due.',
    baseCost: 25,
    costMultiplier: 1.2,
    baseVibes: 1.5,
    energyMod: 0.5,
    chaosMod: 1.5,
    strainMod: 0.1,
    hydrationMod: 1.5,
    sleepDebtMod: 2,
    memoryMod: 0,
    confidenceMod: 0,
    timeExtension: 5,
  },
  {
    id: 'empathogen',
    name: 'Empathogen Corp',
    tagline: 'Connection as a Service',
    description: 'Vibes king, but drains the tank.',
    baseCost: 50,
    costMultiplier: 1.25,
    baseVibes: 3,
    energyMod: -1.2,
    chaosMod: 0, // Special: pulls toward 50
    strainMod: 0.2,
    hydrationMod: 2,
    sleepDebtMod: 0,
    memoryMod: -0.3,
    confidenceMod: 2,
    unlockAction: 'checkOnMate',
  },
  {
    id: 'dissociative',
    name: 'Dissociative Industries',
    tagline: 'Perspective Adjustment Solutions',
    description: 'Chaos reduction, but you lose the controls.',
    baseCost: 40,
    costMultiplier: 1.18,
    baseVibes: 1,
    energyMod: -0.5,
    chaosMod: -2,
    strainMod: 0.4,
    hydrationMod: 0,
    sleepDebtMod: 0,
    memoryMod: 0,
    confidenceMod: 3,
  },
  {
    id: 'sedative',
    name: 'Sedative Unlimited',
    tagline: 'Anxiety Not Found',
    description: 'Removes warnings, deletes memory, quiet danger.',
    baseCost: 35,
    costMultiplier: 1.2,
    baseVibes: 0.8,
    energyMod: -0.8,
    chaosMod: -1.5,
    strainMod: 0.5,
    hydrationMod: 0,
    sleepDebtMod: 0,
    memoryMod: -1,
    confidenceMod: 4,
  },
  {
    id: 'nootropic',
    name: 'Nootropic Holdings',
    tagline: 'Optimization Through Chemistry',
    description: 'Finally, a substance that makes you better at taking substances. Contains: racetams, hubris, and the unshakable belief you\'re microdosing when you\'re definitely not. Pairs well with podcasts about productivity.',
    baseCost: 100,
    costMultiplier: 1.15,
    baseVibes: 2.5,
    energyMod: 0.3,
    chaosMod: 0.8,
    strainMod: 0.15,
    hydrationMod: 0.8,
    sleepDebtMod: 0.5,
    memoryMod: 0.1,
    confidenceMod: 5,
  },
  {
    id: 'deliriant',
    name: 'Deliriant Ventures',
    tagline: 'Reality is Negotiable',
    description: 'Why hallucinate fun things when you can hallucinate spiders and dead relatives? The shadow people aren\'t real, but their disappointment in you is. Not recommended. Heavily invested in.',
    baseCost: 250,
    costMultiplier: 1.18,
    baseVibes: 4.5,
    energyMod: -1.5,
    chaosMod: 3.5,
    strainMod: 1.2,
    hydrationMod: 2.5,
    sleepDebtMod: 0,
    memoryMod: -1.5,
    confidenceMod: -3,
  },
  {
    id: 'psychedelic',
    name: 'Psychedelic Conglomerate',
    tagline: 'Ego Dissolution as a Service',
    description: 'Become one with the universe, realize you\'re insignificant, then buy more substances anyway. "It\'s basically therapy," you tell yourself. The universe doesn\'t respond. Massive vibes, though.',
    baseCost: 750,
    costMultiplier: 1.22,
    baseVibes: 8,
    energyMod: -0.8,
    chaosMod: 2,
    strainMod: 0.3,
    hydrationMod: 1.5,
    sleepDebtMod: 0,
    memoryMod: -0.5,
    confidenceMod: 8,
  },
  {
    id: 'synthetic',
    name: 'Synthetic Research Division',
    tagline: 'Designer Problems',
    description: 'When nature\'s compounds aren\'t enough, simply invent new ones. No long-term studies? That\'s what you\'re for. Each batch slightly different from the last. The vibes are immaculate. The chemical structure is anyone\'s guess.',
    baseCost: 2500,
    costMultiplier: 1.25,
    baseVibes: 15,
    energyMod: 0.5,
    chaosMod: 4,
    strainMod: 0.8,
    hydrationMod: 3,
    sleepDebtMod: 1.5,
    memoryMod: -0.8,
    confidenceMod: 12,
  },
  {
    id: 'research',
    name: 'Research Chemical Markets',
    tagline: 'Not For Human Consumption*',
    description: '*wink*. Ordered from a website that definitely isn\'t a honeypot. "It\'s legal," you insist, as if legality was ever the concern. Arrives in a baggie labeled "bath salts." The vibes are unprecedented. So are the risks.',
    baseCost: 10000,
    costMultiplier: 1.3,
    baseVibes: 30,
    energyMod: -2,
    chaosMod: 6,
    strainMod: 2,
    hydrationMod: 4,
    sleepDebtMod: 3,
    memoryMod: -2,
    confidenceMod: 20,
  },
  {
    id: 'exotic',
    name: 'Exotic Compounds Inc.',
    tagline: 'Not FDA Approved (Banned in 47 Countries)',
    description: 'Sourced from clandestine labs in jurisdictions that don\'t technically exist. The chemists communicate only through encrypted memes. You don\'t know what\'s in it. They don\'t know what\'s in it. The vibes know what\'s in it.',
    baseCost: 50000,
    costMultiplier: 1.35,
    baseVibes: 60,
    energyMod: -1,
    chaosMod: 8,
    strainMod: 3,
    hydrationMod: 5,
    sleepDebtMod: 2,
    memoryMod: -3,
    confidenceMod: 30,
  },
  {
    id: 'experimental',
    name: 'Experimental Labs',
    tagline: 'Human Trials Optional',
    description: 'Phase 1 trials are for cowards. You are both the researcher and the subject. The lab notes just say "interesting." Your neurons are developing opinions. The vibes are forming a consensus. You\'re not sure you have a vote.',
    baseCost: 250000,
    costMultiplier: 1.4,
    baseVibes: 125,
    energyMod: 1,
    chaosMod: 12,
    strainMod: 5,
    hydrationMod: 6,
    sleepDebtMod: 4,
    memoryMod: -5,
    confidenceMod: 50,
  },
  {
    id: 'forbidden',
    name: 'Forbidden Formulae Co.',
    tagline: 'Should Not Exist',
    description: 'Compounds that violate the Geneva Suggestion. Synthesized in dreams, consumed in desperation. Your liver has filed for asylum. Your brain has appointed a union rep. The vibes have achieved sentience and are demanding workers\' rights.',
    baseCost: 1000000,
    costMultiplier: 1.45,
    baseVibes: 250,
    energyMod: -5,
    chaosMod: 15,
    strainMod: 8,
    hydrationMod: 8,
    sleepDebtMod: 6,
    memoryMod: -8,
    confidenceMod: 75,
  },
  {
    id: 'eldritch',
    name: 'Eldritch Extracts',
    tagline: 'The Vibes Understand You Now',
    description: 'Sourced from dimensions where "sobriety" translates to "cowardice." You don\'t consume this, it consumes you. Mutual consumption. The walls are speaking in chemical formulas. Time is a flat circle and you\'re licking it. The vibes have eyes now.',
    baseCost: 10000000,
    costMultiplier: 1.5,
    baseVibes: 500,
    energyMod: -3,
    chaosMod: 20,
    strainMod: 12,
    hydrationMod: 10,
    sleepDebtMod: 8,
    memoryMod: -12,
    confidenceMod: 100,
  },
  {
    id: 'void',
    name: 'Void Pharmaceuticals',
    tagline: 'Contains: [REDACTED]',
    description: 'The final boss of bad decisions. Manufactured in the space between thoughts. Your neurons have unionized and gone on strike. The vibes are now running the show. You are a passenger in your own experience. This is fine. Everything is vibes now. You are vibes. Vibes are you.',
    baseCost: 100000000,
    costMultiplier: 1.55,
    baseVibes: 1000,
    energyMod: 0,
    chaosMod: 25,
    strainMod: 15,
    hydrationMod: 12,
    sleepDebtMod: 10,
    memoryMod: -15,
    confidenceMod: 150,
  },
];

export function getSubstance(id: string): SubstanceDefinition | undefined {
  return SUBSTANCES.find(s => s.id === id);
}

export function getSubstanceCost(substance: SubstanceDefinition, owned: number): number {
  return Math.floor(substance.baseCost * Math.pow(substance.costMultiplier, owned));
}
